import { fireEvent, render, screen } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { MobileShell } from './MobileShell';

const mockUseMobileChatTurns = vi.fn();
const mockUseStructuredSession = vi.fn();
const mockListSessionGitBranches = vi.fn(() => Promise.resolve({ branches: [], currentBranch: null }));
const mockCheckoutSessionGitBranch = vi.fn(() => Promise.resolve({ branches: [], currentBranch: null }));

vi.mock('./TerminalChat', () => ({
  TerminalChat(props) {
    return (
      <div
        data-testid="terminal-chat"
        data-session-id={props.sessionId}
        data-surface={props.surface}
        data-input-enabled={props.inputEnabled === false ? 'false' : 'true'}
      />
    );
  },
}));

vi.mock('./DesktopConversationView', () => ({
  DesktopConversationView(props) {
    return (
      <div data-testid="desktop-conversation-view">
        <button type="button" onClick={() => props.onOpenTerminal?.()}>
          Open terminal view
        </button>
      </div>
    );
  },
}));

vi.mock('./DesktopStatusBar', () => ({
  DesktopStatusBar(props) {
    return (
      <div
        data-testid="desktop-status-bar"
        data-terminal-open={props.isTerminalPanelOpen ? 'true' : 'false'}
        data-show-terminal-toggle={props.showTerminalToggle ? 'true' : 'false'}
      >
        <textarea
          aria-label="Command composer"
          placeholder={props.composerPlaceholder}
          value={props.composerValue}
          onChange={(event) => props.onComposerChange?.(event.target.value)}
        />
        <button type="button" onClick={() => props.onComposerSubmit?.(props.composerValue)}>
          Send composer
        </button>
        {props.showTerminalToggle ? (
          <button type="button" onClick={() => props.onToggleTerminalPanel?.()}>
            Toggle terminal
          </button>
        ) : null}
      </div>
    );
  },
}));

vi.mock('../hooks/useMobileChatTurns', () => ({
  useMobileChatTurns(args) {
    return mockUseMobileChatTurns(args);
  },
}));

vi.mock('../hooks/useStructuredSession', () => ({
  useStructuredSession(args) {
    return mockUseStructuredSession(args);
  },
}));

vi.mock('../contexts/TerminalSessionContext', () => ({
  useTerminalSession() {
    return {
      listSessionGitBranches: mockListSessionGitBranches,
      checkoutSessionGitBranch: mockCheckoutSessionGitBranch,
    };
  },
}));

const BASE_SESSIONS = [
  {
    id: 'session-a',
    title: 'Main terminal',
    cwd: 'C:/work/terminal-v4',
    thread: {
      topic: 'Ship mobile parity',
      topicAutoGenerated: false,
      projectPath: 'C:/work/terminal-v4',
    },
  },
  {
    id: 'session-b',
    title: 'Docs terminal',
    cwd: 'C:/work/docs',
    thread: {
      topic: 'Review release checklist',
      topicAutoGenerated: false,
      projectPath: 'C:/work/docs',
    },
  },
];

function createMobileChatTurnsState() {
  return {
    turns: [],
    isLoading: false,
    isSendReady: true,
    handleTurn: vi.fn(),
    handleRegisterSendText: vi.fn(),
    handleChatSend: vi.fn(() => ({ queued: false })),
    handleRawSend: vi.fn(() => ({ queued: false })),
    handleInterrupt: vi.fn(() => ({ queued: false })),
  };
}

function createStructuredSessionState() {
  return {
    messages: [],
    currentToolCalls: [],
    pendingApproval: null,
    isStreaming: false,
    connectionState: 'online',
    sendMessage: vi.fn(),
    interrupt: vi.fn(),
    approve: vi.fn(),
  };
}

function renderMobileShell(overrides = {}) {
  const sessions = overrides.sessions ?? BASE_SESSIONS;
  return render(
    <MobileShell
      sessions={sessions}
      activeSessionId={overrides.activeSessionId ?? sessions[0]?.id ?? null}
      onSelectSession={overrides.onSelectSession ?? vi.fn()}
      onCreateSession={overrides.onCreateSession ?? vi.fn()}
      projectInfo={overrides.projectInfo ?? { cwd: 'C:/work/terminal-v4', gitBranch: 'main' }}
      sessionActivity={overrides.sessionActivity ?? {}}
      onSessionBusyChange={overrides.onSessionBusyChange ?? vi.fn()}
      fontSize={14}
      webglEnabled
      viewportHeight={800}
      mobileView="terminal"
      onViewChange={overrides.onViewChange ?? vi.fn()}
      chatMode={false}
      onChatModeChange={overrides.onChatModeChange ?? vi.fn()}
      accessoryOpen={overrides.accessoryOpen ?? false}
      onAccessoryToggle={overrides.onAccessoryToggle ?? vi.fn()}
      onAccessoryHeightChange={overrides.onAccessoryHeightChange ?? vi.fn()}
      onRegisterFocusTerminal={overrides.onRegisterFocusTerminal ?? vi.fn()}
      onUrlDetected={overrides.onUrlDetected ?? vi.fn()}
      sessionAiTypes={overrides.sessionAiTypes ?? { 'session-a': 'codex', 'ss-structured': 'codex' }}
      customAiProviders={overrides.customAiProviders ?? []}
      onSetSessionAiType={overrides.onSetSessionAiType ?? vi.fn()}
      onAddCustomAiProvider={overrides.onAddCustomAiProvider ?? vi.fn()}
    />
  );
}

describe('MobileShell', () => {
  beforeEach(() => {
    mockUseMobileChatTurns.mockReturnValue(createMobileChatTurnsState());
    mockUseStructuredSession.mockReturnValue(createStructuredSessionState());
    mockListSessionGitBranches.mockClear();
    mockCheckoutSessionGitBranch.mockClear();
  });

  it('uses the desktop composer flow for terminal-first mobile sessions', () => {
    const mobileChatState = createMobileChatTurnsState();
    mockUseMobileChatTurns.mockReturnValue(mobileChatState);

    renderMobileShell();

    expect(mockUseMobileChatTurns).toHaveBeenCalledWith({ sessionId: 'session-a', chatMode: true });
    expect(screen.getByTestId('terminal-chat')).toHaveAttribute('data-session-id', 'session-a');
    expect(screen.getByTestId('terminal-chat')).toHaveAttribute('data-surface', 'mobile');
    expect(screen.getByPlaceholderText('Ask V4 anything')).toBeInTheDocument();

    fireEvent.change(screen.getByLabelText('Command composer'), {
      target: { value: 'Fix the mobile composer layout' },
    });
    fireEvent.click(screen.getByRole('button', { name: 'Send composer' }));

    expect(mobileChatState.handleChatSend).toHaveBeenCalledWith('Fix the mobile composer layout');
  });

  it('uses the desktop structured-session flow and can open the inline terminal', () => {
    const sessions = [
      {
        id: 'ss-structured',
        title: 'Structured session',
        cwd: 'C:/work/terminal-v4',
        thread: {
          topic: 'Structured agent session',
          topicAutoGenerated: false,
          projectPath: 'C:/work/terminal-v4',
        },
      },
    ];

    renderMobileShell({
      sessions,
      activeSessionId: 'ss-structured',
    });

    expect(mockUseMobileChatTurns).toHaveBeenCalledWith({ sessionId: 'ss-structured', chatMode: false });
    expect(mockUseStructuredSession).toHaveBeenCalledWith({ sessionId: 'ss-structured', active: true });
    expect(screen.getByTestId('desktop-conversation-view')).toBeInTheDocument();
    expect(screen.getByTestId('desktop-status-bar')).toHaveAttribute('data-show-terminal-toggle', 'true');
    expect(screen.getByTestId('terminal-chat')).toHaveAttribute('data-input-enabled', 'false');

    fireEvent.click(screen.getByRole('button', { name: 'Open terminal view' }));

    expect(screen.getByTestId('desktop-status-bar')).toHaveAttribute('data-terminal-open', 'true');
    expect(screen.getByTestId('terminal-chat')).toHaveAttribute('data-input-enabled', 'true');
  });

  it('switches sessions from the mobile session rail', () => {
    const onSelectSession = vi.fn();

    renderMobileShell({ onSelectSession });

    fireEvent.click(screen.getByRole('tab', { name: /review release checklist/i }));

    expect(onSelectSession).toHaveBeenCalledWith('session-b');
  });
});
