import { useRef, useState, useCallback, useEffect, memo } from 'react';
import { TerminalChat } from './TerminalChat';
import { DesktopStatusBar } from './DesktopStatusBar';
import { useMobileChatTurns } from '../hooks/useMobileChatTurns';
import { useStructuredSession } from '../hooks/useStructuredSession';
import { DesktopConversationView } from './DesktopConversationView';
import { shouldFallbackToTerminalView } from '../utils/conversationMode';
import { getAiCapabilities, getAiLaunchCommand } from '../utils/aiProviders';

const ANSI_ESCAPE_RE = /\x1b\[[0-?]*[ -/]*[@-~]/g;

function extractTerminalPreviewLines(chunk) {
  if (typeof chunk !== 'string' || chunk.length === 0) return [];

  return chunk
    .replace(ANSI_ESCAPE_RE, '')
    .replace(/\x1b\][^\x07]*(?:\x07|\x1b\\)/g, '')
    .replace(/\r/g, '\n')
    .replace(/\x08/g, '')
    .replace(/[^\x09\x0a\x20-\x7e]/g, '')
    .split('\n')
    .map(line => line.trimEnd())
    .filter(Boolean);
}

function isReasonablePaneSummary(topic, isAutoGenerated) {
  if (typeof topic !== 'string') return false;
  const text = topic.trim();
  if (!text) return false;
  if (!isAutoGenerated) return true;

  // Auto-generated topics sometimes capture broken wrapped terminal fragments.
  if (/^[^A-Za-z0-9("'[]/.test(text)) return false;
  if (/[.·•]{2,}/.test(text.slice(0, 12))) return false;
  if (/[\x00-\x1f]/.test(text)) return false;

  const letters = (text.match(/[A-Za-z]/g) ?? []).length;
  if (letters / text.length < 0.4) return false;

  return true;
}

export const TerminalPane = memo(function TerminalPane({
  pane,
  isActive,
  isFullscreen,
  sessions,
  canSplit,
  canClose,
  onSessionSelect,
  onSplit,
  onClose,
  onFocus,
  onFullscreen,
  showPreview,
  onMinimizeMainTerminal,
  keybarOpen,
  viewportHeight,
  onUrlDetected,
  fontSize,
  webglEnabled,
  sessionActivity,
  projectInfo,
  sessionAiTypes,
  onCwdChange,
  onSessionBusyChange,
  currentDesktopId,
  fitSignal
}) {
  const paneRef = useRef(null);
  const imageInputRef = useRef(null);
  const menuRef = useRef(null);
  const [isDragOver, setIsDragOver] = useState(false);
  const [isHeaderDragging, setIsHeaderDragging] = useState(false);
  const [showSessionMenu, setShowSessionMenu] = useState(false);
  const [connectionState, setConnectionState] = useState('connecting');
  const [currentCwd, setCurrentCwd] = useState(null);
  const [refreshToken, setRefreshToken] = useState(0);
  const [isSessionBusy, setIsSessionBusy] = useState(false);
  const [launchQueued, setLaunchQueued] = useState(false);
  const [viewModeNotice, setViewModeNotice] = useState('');
  const [isNoticePersistent, setIsNoticePersistent] = useState(false);
  const [terminalPreview, setTerminalPreview] = useState('');
  const [terminalScreenSnapshot, setTerminalScreenSnapshot] = useState('');
  const [interactivePromptEvent, setInteractivePromptEvent] = useState(null);
  const [isTerminalPanelOpen, setIsTerminalPanelOpen] = useState(false);
  const conversationFallbackRef = useRef(false);
  const interactivePromptRef = useRef(null);
  const outputProbeRef = useRef('');
  const hasConnectedOnceRef = useRef(false);
  const handleToggleTerminalPanel = useCallback(() => {
    setIsTerminalPanelOpen((isOpen) => {
      const next = !isOpen;
      if (next) {
        conversationFallbackRef.current = false;
        setIsNoticePersistent(false);
        setViewModeNotice('');
      }
      return next;
    });
  }, []);

  const currentSession = sessions.find(s => s.id === pane.sessionId);
  const currentAiType = sessionAiTypes?.[pane.sessionId] ?? null;
  const currentAiCapabilities = getAiCapabilities(currentAiType);
  const launchCommand = getAiLaunchCommand(currentAiType);
  const rawTopic = currentSession?.thread?.topic || null;
  const useTopic = isReasonablePaneSummary(rawTopic, currentSession?.thread?.topicAutoGenerated);
  const paneSummaryText = (useTopic ? rawTopic : null) || currentSession?.title || null;
  // Detect if session uses structured mode (ss- prefix)
  const isStructuredSession = Boolean(pane.sessionId && pane.sessionId.startsWith('ss-'));

  const {
    turns,
    isLoading: isConversationHistoryLoading,
    isSendReady,
    handleTurn,
    handleRegisterSendText,
    handleChatSend,
    handleRawSend,
    handleInterrupt,
  } = useMobileChatTurns({
    sessionId: pane.sessionId ?? null,
    chatMode: Boolean(pane.sessionId) && !isStructuredSession,
  });

  const {
    messages: structuredMessages,
    currentToolCalls: structuredToolCalls,
    pendingApproval,
    isStreaming: structuredIsStreaming,
    connectionState: structuredConnectionState,
    sendMessage: structuredSendMessage,
    interrupt: structuredInterrupt,
    approve: structuredApprove,
  } = useStructuredSession({
    sessionId: isStructuredSession ? pane.sessionId : null,
    active: isStructuredSession,
  });

  useEffect(() => {
    if (!viewModeNotice || isNoticePersistent) return;
    const timer = setTimeout(() => setViewModeNotice(''), 5000);
    return () => clearTimeout(timer);
  }, [viewModeNotice, isNoticePersistent]);

  useEffect(() => {
    setIsSessionBusy(false);
    setIsTerminalPanelOpen(false);
    setConnectionState('connecting');
    setLaunchQueued(false);
    setTerminalPreview('');
    setTerminalScreenSnapshot('');
    setInteractivePromptEvent(null);
    setViewModeNotice('');
    setIsNoticePersistent(false);
    conversationFallbackRef.current = false;
    interactivePromptRef.current = null;
    outputProbeRef.current = '';
    hasConnectedOnceRef.current = false;
  }, [pane.sessionId]);

  useEffect(() => {
    if (!isSendReady || !launchQueued) return;
    setLaunchQueued(false);
    setIsNoticePersistent(false);
    setViewModeNotice('Queued launch command sent to terminal.');
  }, [isSendReady, launchQueued]);

  // Close session menu on outside click
  useEffect(() => {
    if (!showSessionMenu) return;
    const handleClickOutside = (e) => {
      if (menuRef.current && !menuRef.current.contains(e.target)) {
        setShowSessionMenu(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [showSessionMenu]);

  const handlePaneClick = (e) => {
    if (!e.target.closest('.ph-controls') && !e.target.closest('.ph-session-menu')) {
      onFocus(pane.id);
    }
  };

  const handleDragOver = useCallback((e) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
    setIsDragOver(true);
  }, []);

  const handleDragLeave = useCallback(() => {
    setIsDragOver(false);
  }, []);

  const handleDrop = useCallback((e) => {
    e.preventDefault();
    setIsDragOver(false);
    const sessionId = e.dataTransfer.getData('session-id');
    if (sessionId) {
      onSessionSelect(pane.id, sessionId);
    }
  }, [pane.id, onSessionSelect]);

  const handleSessionClick = useCallback((e) => {
    e.stopPropagation();
    setShowSessionMenu(prev => !prev);
  }, []);

  const handleSessionSelect = useCallback((sessionId) => {
    onSessionSelect(pane.id, sessionId);
    setShowSessionMenu(false);
  }, [pane.id, onSessionSelect]);

  const handleImageUpload = useCallback(() => {
    imageInputRef.current?.click();
  }, []);

  const handleConnectionChange = useCallback((connected) => {
    if (connected) {
      hasConnectedOnceRef.current = true;
      setConnectionState('online');
      return;
    }
    setConnectionState(hasConnectedOnceRef.current ? 'offline' : 'connecting');
  }, []);

  const handleActivityChange = useCallback((isBusy) => {
    setIsSessionBusy(Boolean(isBusy));
    onSessionBusyChange?.(pane.sessionId, isBusy);
  }, [onSessionBusyChange, pane.sessionId]);

  const handleOutputChunk = useCallback((chunk) => {
    if (typeof chunk !== 'string' || chunk.length === 0) return;

    if (interactivePromptRef.current) {
      const normalizedChunk = chunk.toLowerCase();
      const stillLooksInteractive =
        /\[[yYnN]\/[yYnN]\]/.test(chunk)
        || normalizedChunk.includes('enter to confirm')
        || normalizedChunk.includes('esc to cancel')
        || normalizedChunk.includes('tab to cycle');
      if (!stillLooksInteractive) {
        interactivePromptRef.current = null;
        setInteractivePromptEvent(null);
      }
    }

    const previewLines = extractTerminalPreviewLines(chunk);
    if (previewLines.length > 0) {
      setTerminalPreview((previous) => {
        const prevLines = previous ? previous.split('\n') : [];
        const next = [...prevLines, ...previewLines].slice(-8).join('\n');
        return next === previous ? previous : next;
      });
    }

    if (conversationFallbackRef.current) return;

    outputProbeRef.current = `${outputProbeRef.current}${chunk}`.slice(-4000);
    if (!shouldFallbackToTerminalView(outputProbeRef.current)) return;

    conversationFallbackRef.current = true;
    setIsNoticePersistent(true);
    setViewModeNotice(
      currentAiCapabilities.prefersStructuredUi
        ? 'Interactive CLI state detected. Conversation stays active - use inline prompt controls or open terminal panel if needed.'
        : 'Interactive CLI prompt detected. Conversation stays active - open terminal panel if you need to answer it.'
    );
  }, [currentAiCapabilities.prefersStructuredUi]);

  const handleCliEvent = useCallback((event) => {
    if (!event || typeof event !== 'object') return;

    if (event.type === 'prompt_required') {
      interactivePromptRef.current = event;
      setInteractivePromptEvent(event);
      setIsNoticePersistent(true);
      setViewModeNotice('Interactive CLI prompt detected. Use inline controls or open terminal panel.');
      return;
    }

    if (event.type === 'assistant_turn' || event.type === 'user_turn') {
      interactivePromptRef.current = null;
      setInteractivePromptEvent(null);
    }
  }, []);

  const handleScreenSnapshot = useCallback((snapshot) => {
    const next = typeof snapshot?.text === 'string' ? snapshot.text : '';
    setTerminalScreenSnapshot((previous) => (previous === next ? previous : next));
  }, []);

  const handleOpenTerminalPanel = useCallback(() => {
    setIsTerminalPanelOpen(true);
    conversationFallbackRef.current = false;
    setIsNoticePersistent(false);
    setViewModeNotice('');
  }, []);

  const handleLaunchAgent = useCallback(() => {
    if (!launchCommand) return;
    interactivePromptRef.current = null;
    setInteractivePromptEvent(null);
    const result = handleChatSend(launchCommand);
    if (result?.queued) {
      setLaunchQueued(true);
      setIsNoticePersistent(false);
      setViewModeNotice('Terminal is still connecting. Launch command queued.');
      return;
    }
    setLaunchQueued(false);
    setIsNoticePersistent(false);
    setViewModeNotice(`Launching ${launchCommand}...`);
  }, [handleChatSend, launchCommand]);

  const handleCwdChange = useCallback((cwd) => {
    setCurrentCwd(cwd);
    onCwdChange?.(cwd);
  }, [onCwdChange]);

  const handleRefreshTerminal = useCallback(() => {
    setRefreshToken((value) => value + 1);
  }, []);

  const handleHeaderDragStart = useCallback((e) => {
    if (!pane.sessionId) return;
    e.dataTransfer.setData('pane-drag', JSON.stringify({
      paneId: pane.id,
      sessionId: pane.sessionId,
      fromDesktopId: currentDesktopId
    }));
    e.dataTransfer.effectAllowed = 'move';
    setIsHeaderDragging(true);
  }, [pane.id, pane.sessionId, currentDesktopId]);

  const handleHeaderDragEnd = useCallback(() => {
    setIsHeaderDragging(false);
  }, []);

  return (
    <div
      ref={paneRef}
      className={`split-terminal-pane ${isActive ? 'active' : ''} ${isFullscreen ? 'fullscreen' : ''} ${isDragOver ? 'drag-over' : ''}${sessionAiTypes?.[pane.sessionId] ? ` pane-ai-${sessionAiTypes[pane.sessionId]}` : ''}`}
      onClick={handlePaneClick}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      <div
        className={`ph-bar${isHeaderDragging ? ' is-dragging-pane' : ''}`}
        draggable={Boolean(pane.sessionId)}
        onDragStart={handleHeaderDragStart}
        onDragEnd={handleHeaderDragEnd}
      >
        <div className="ph-left">
          {/* Session selector - only in split mode with multiple sessions */}
          {canClose && sessions.length > 1 && (
            <div className="ph-session" ref={menuRef}>
              <button
                type="button"
                className="ph-session-btn"
                onClick={handleSessionClick}
              >
                <span className="ph-session-dot" />
                <span className="ph-session-name">
                  {currentSession?.title || 'No session'}
                </span>
                <svg className="ph-session-chevron" width="8" height="8" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </button>

              {showSessionMenu && (
                <div className="ph-session-menu">
                  <div className="ph-menu-label">Switch session</div>
                  {sessions.map(session => {
                    const hasUnread = sessionActivity?.[session.id]?.hasUnread;
                    const isCurrentSession = session.id === pane.sessionId;
                    return (
                      <button
                        key={session.id}
                        type="button"
                        className={`ph-menu-item ${isCurrentSession ? 'active' : ''}`}
                        onClick={() => handleSessionSelect(session.id)}
                      >
                        {hasUnread && <span className="ph-menu-dot" />}
                        <span className="ph-menu-title">{session.title}</span>
                        {isCurrentSession && (
                          <svg className="ph-menu-check" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                            <polyline points="20 6 9 17 4 12" />
                          </svg>
                        )}
                      </button>
                    );
                  })}
                  {sessions.length === 0 && (
                    <div className="ph-menu-empty">No sessions available</div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* Session topic summary */}
          {paneSummaryText && (
            <>
              {canClose && sessions.length > 1 && <span className="ph-topic-sep">·</span>}
              <span className="ph-topic" title={paneSummaryText}>
                {paneSummaryText}
              </span>
            </>
          )}
        </div>

        <div className="ph-controls">
          {/* Reconnect */}
          <button
            className="ph-btn"
            onClick={(e) => { e.stopPropagation(); handleRefreshTerminal(); }}
            title="Reconnect terminal"
          >
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="23 4 23 10 17 10" />
              <path d="M20.49 15a9 9 0 1 1 2.13-9" />
            </svg>
          </button>

          {/* Split buttons */}
          {canSplit && !isFullscreen && (
            <>

              <button
                className="ph-btn"
                onClick={(e) => { e.stopPropagation(); onSplit(pane.id, 'horizontal'); }}
                title="Split horizontally"
              >
                <svg width="13" height="13" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <rect x="1" y="2" width="5" height="10" rx="1" />
                  <rect x="8" y="2" width="5" height="10" rx="1" />
                </svg>
              </button>
              <button
                className="ph-btn"
                onClick={(e) => { e.stopPropagation(); onSplit(pane.id, 'vertical'); }}
                title="Split vertically"
              >
                <svg width="13" height="13" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <rect x="2" y="1" width="10" height="5" rx="1" />
                  <rect x="2" y="8" width="10" height="5" rx="1" />
                </svg>
              </button>
            </>
          )}

          {/* Minimize to show preview */}
          {showPreview && !isFullscreen && onMinimizeMainTerminal && (
            <>

              <button
                className="ph-btn"
                onClick={(e) => { e.stopPropagation(); onMinimizeMainTerminal(); }}
                title="Minimize terminal (show browser)"
              >
                <svg width="13" height="13" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                  <rect x="1" y="2" width="6" height="10" rx="1" />
                  <polyline points="8 5 11 7 8 9" />
                </svg>
              </button>
            </>
          )}

          {/* Fullscreen */}
          <span className="ph-divider" />
          <button
            className="ph-btn"
            onClick={(e) => { e.stopPropagation(); onFullscreen(pane.id); }}
            title={isFullscreen ? 'Exit fullscreen' : 'Fullscreen'}
          >
            {isFullscreen ? (
              <svg width="13" height="13" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5">
                <polyline points="4 10 1 10 1 13" />
                <polyline points="10 4 13 4 13 1" />
                <line x1="1" y1="13" x2="5" y2="9" />
                <line x1="9" y1="5" x2="13" y2="1" />
              </svg>
            ) : (
              <svg width="13" height="13" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5">
                <polyline points="10 1 13 1 13 4" />
                <polyline points="4 13 1 13 1 10" />
                <line x1="13" y1="1" x2="9" y2="5" />
                <line x1="1" y1="13" x2="5" y2="9" />
              </svg>
            )}
          </button>

          {/* Close pane */}
          {canClose && !isFullscreen && (
            <button
              className="ph-btn ph-btn-close"
              onClick={(e) => { e.stopPropagation(); onClose(pane.id); }}
              title="Close pane"
            >
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </button>
          )}
        </div>
      </div>

      <div className="pane-content">
        {pane.sessionId ? (
          <div className="terminal-with-status">
            <div className={`desktop-terminal-stack${isTerminalPanelOpen ? ' terminal-panel-open' : ''}`}>
              <div className="desktop-conversation-surface">
                <DesktopConversationView
                  turns={turns}
                  isStreaming={isStructuredSession ? structuredIsStreaming : isSessionBusy}
                  isLoadingHistory={isConversationHistoryLoading}
                  onSend={isStructuredSession ? structuredSendMessage : handleChatSend}
                  onSendRaw={handleRawSend}
                  onInterrupt={isStructuredSession ? structuredInterrupt : handleInterrupt}
                  onImageUpload={handleImageUpload}
                  sessionId={pane.sessionId}
                  aiType={currentAiType}
                  connectionState={isStructuredSession ? structuredConnectionState : connectionState}
                  isSendReady={isStructuredSession ? true : isSendReady}
                  terminalPreview={terminalPreview}
                  terminalScreenSnapshot={terminalScreenSnapshot}
                  launchCommand={isStructuredSession ? '' : launchCommand}
                  launchQueued={launchQueued}
                  onLaunchAgent={handleLaunchAgent}
                  onOpenTerminal={handleOpenTerminalPanel}
                  conversationNotice={viewModeNotice}
                  showTerminalMirror={Boolean(interactivePromptEvent) || isNoticePersistent}
                  interactivePromptEvent={interactivePromptEvent}
                  mode={isStructuredSession ? 'structured' : 'terminal'}
                  structuredMessages={structuredMessages}
                  structuredToolCalls={structuredToolCalls}
                  pendingApproval={pendingApproval}
                  onApprove={structuredApprove}
                />
              </div>

              <div
                className={`desktop-terminal-runtime${isTerminalPanelOpen ? ' inline-panel-open' : ' is-hidden'}`}
                aria-hidden={!isTerminalPanelOpen ? 'true' : undefined}
              >
                <TerminalChat
                  key={`${pane.sessionId}-${refreshToken}`}
                  sessionId={pane.sessionId}
                  keybarOpen={keybarOpen}
                  viewportHeight={viewportHeight}
                  onUrlDetected={onUrlDetected}
                  fontSize={fontSize}
                  webglEnabled={webglEnabled}
                  usesTmux={currentSession?.usesTmux}
                  viewMode="terminal"
                  isPrimary={isActive}
                  fitSignal={fitSignal}
                  onRegisterImageUpload={(trigger) => { imageInputRef.current = { click: trigger }; }}
                  onConnectionChange={handleConnectionChange}
                  onCwdChange={handleCwdChange}
                  onActivityChange={handleActivityChange}
                  onOutputChunk={handleOutputChunk}
                  onScreenSnapshot={handleScreenSnapshot}
                  onCliEvent={handleCliEvent}
                  onRegisterSendText={handleRegisterSendText}
                  onTurn={handleTurn}
                />
              </div>
            </div>
            <DesktopStatusBar
              sessionId={pane.sessionId}
              sessionTitle={currentSession?.title}
              cwd={currentCwd || projectInfo?.cwd}
              gitBranch={projectInfo?.gitBranch}
              onImageUpload={handleImageUpload}
              isTerminalPanelOpen={isTerminalPanelOpen}
              onToggleTerminalPanel={handleToggleTerminalPanel}
              connectionState={connectionState}
              aiType={currentAiType}
            />
          </div>
        ) : (
          <div className="pane-empty">
            <p>Select a session or drag one here</p>
          </div>
        )}
      </div>

      <style>{`
        /* ── Pane header bar ── */
        .ph-bar {
          display: flex;
          align-items: center;
          justify-content: space-between;
          height: 36px;
          padding: 0 6px 0 10px;
          background: var(--bg-surface);
          border-bottom: 1px solid var(--border-subtle);
          flex-shrink: 0;
        }

        .ph-bar[draggable=true] { cursor: grab; }
        .ph-bar.is-dragging-pane { opacity: 0.5; cursor: grabbing; }

        .ph-left {
          display: flex;
          align-items: center;
          min-width: 0;
          flex: 1;
        }

        /* ── Topic summary ── */
        .ph-topic-sep {
          color: var(--text-muted);
          opacity: 0.5;
          padding: 0 6px;
          flex-shrink: 0;
          font-size: 12px;
        }

        .ph-topic {
          font-size: 11px;
          color: var(--text-muted);
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
          max-width: 220px;
          flex-shrink: 1;
        }

        /* ── Session selector ── */
        .ph-session {
          position: relative;
        }

        .ph-session-btn {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 4px 8px 4px 8px;
          background: var(--bg-elevated);
          border: 1px solid var(--border-subtle);
          border-radius: var(--radius-sm, 4px);
          color: var(--text-secondary);
          font-size: 12px;
          font-weight: 500;
          cursor: pointer;
          transition: all var(--transition-fast, 0.15s ease);
        }

        .ph-session-btn:hover {
          border-color: var(--accent-primary);
          color: var(--accent-primary);
        }

        .ph-session-dot {
          width: 6px;
          height: 6px;
          border-radius: 50%;
          background: var(--accent-primary);
          opacity: 0.7;
          flex-shrink: 0;
        }

        .ph-session-name {
          max-width: 140px;
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
        }

        .ph-session-chevron {
          opacity: 0.5;
          flex-shrink: 0;
        }

        /* ── Session dropdown menu ── */
        .ph-session-menu {
          position: absolute;
          top: calc(100% + 4px);
          left: 0;
          min-width: 200px;
          max-height: 260px;
          overflow-y: auto;
          background: var(--bg-elevated);
          border: 1px solid var(--border-default);
          border-radius: var(--radius-md, 8px);
          box-shadow: var(--shadow-lg, 0 8px 24px rgba(0, 0, 0, 0.5));
          z-index: 1000;
          padding: 4px;
        }

        .ph-menu-label {
          padding: 6px 10px 4px;
          font-size: 10px;
          font-weight: 650;
          text-transform: uppercase;
          letter-spacing: 0.4px;
          color: var(--text-muted);
        }

        .ph-menu-item {
          display: flex;
          align-items: center;
          gap: 8px;
          width: 100%;
          padding: 6px 10px;
          background: transparent;
          border: none;
          border-radius: var(--radius-sm, 4px);
          color: var(--text-secondary);
          font-size: 12px;
          text-align: left;
          cursor: pointer;
          transition: all var(--transition-fast, 0.15s ease);
        }

        .ph-menu-item:hover {
          background: var(--bg-surface);
          color: var(--text-primary);
        }

        .ph-menu-item.active {
          background: var(--accent-primary-dim);
          color: var(--accent-primary);
        }

        .ph-menu-dot {
          width: 5px;
          height: 5px;
          border-radius: 50%;
          background: var(--accent-primary);
          flex-shrink: 0;
        }

        .ph-menu-title {
          flex: 1;
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
        }

        .ph-menu-check {
          flex-shrink: 0;
          opacity: 0.8;
          color: var(--accent-primary);
        }

        .ph-menu-empty {
          padding: 12px 10px;
          font-size: 11px;
          color: var(--text-muted);
          text-align: center;
        }

        /* ── Control buttons ── */
        .ph-controls {
          display: flex;
          align-items: center;
          gap: 4px;
          flex-shrink: 0;
        }

        .ph-btn {
          background: var(--bg-elevated);
          border: 1px solid var(--border-subtle);
          border-radius: var(--radius-sm, 4px);
          padding: 5px;
          color: var(--text-muted);
          cursor: pointer;
          transition: all var(--transition-fast, 0.15s ease);
          display: flex;
          align-items: center;
          justify-content: center;
          line-height: 1;
        }

        .ph-btn svg {
          display: block;
        }

        .ph-btn:hover {
          background: var(--bg-surface);
          border-color: var(--accent-primary);
          color: var(--accent-primary);
        }

        .ph-btn-close:hover {
          background: rgba(244, 63, 94, 0.1);
          border-color: var(--error);
          color: var(--error);
        }

        @media (max-width: 768px) {
          .ph-btn {
            min-width: 44px;
            min-height: 44px;
            padding: 10px;
          }
        }
      `}</style>
    </div>
  );
});
