import { useRef, useState, useCallback, useEffect, useMemo, memo } from 'react';
import { TerminalChat } from './TerminalChat';
import { DesktopStatusBar } from './DesktopStatusBar';
import { useMobileChatTurns } from '../hooks/useMobileChatTurns';
import { useStructuredSession } from '../hooks/useStructuredSession';
import { DesktopConversationView } from './DesktopConversationView';
import { shouldFallbackToTerminalView } from '../utils/conversationMode';
import { getAiCapabilities, getAiInitialCommand, getAiTypeOptions } from '../utils/aiProviders';
import { getPreferredSessionTopic, isMeaningfulSessionTopic } from '../utils/sessionTopic';
import { parseTerminalRuntimeInfo } from '../utils/terminalRuntimeInfo';
import { useTerminalSession } from '../contexts/TerminalSessionContext';

const ANSI_ESCAPE_RE = /\x1b\[[0-?]*[ -/]*[@-~]/g;

function extractTerminalPreviewLines(chunk) {
  if (typeof chunk !== 'string' || chunk.length === 0) return [];

  return chunk
    .replace(ANSI_ESCAPE_RE, '')
    .replace(/\x1b\][^\x07]*(?:\x07|\x1b\\)/g, '')
    .replace(/\r/g, '\n')
    .replace(/\x08/g, '')
    .replace(/[^\x09\x0a\x20-\x7e]/g, '')
    .split('\n')
    .map(line => line.trimEnd())
    .filter(Boolean);
}

function isReasonablePaneSummary(topic, isAutoGenerated) {
  if (!isMeaningfulSessionTopic(topic)) return false;
  if (typeof topic !== 'string') return false;
  const text = topic.trim();
  if (!text) return false;
  if (!isAutoGenerated) return true;

  // Auto-generated topics sometimes capture broken wrapped terminal fragments.
  if (/^[^A-Za-z0-9("'[]/.test(text)) return false;
  if (/[.·•]{2,}/.test(text.slice(0, 12))) return false;
  if (/[\x00-\x1f]/.test(text)) return false;

  const letters = (text.match(/[A-Za-z]/g) ?? []).length;
  if (letters / text.length < 0.4) return false;

  return true;
}

function getPaneSessionLabel(session) {
  if (!session) return 'Select terminal';
  return getPreferredSessionTopic(session.thread?.topic, session.title || 'New session');
}

export const TerminalPane = memo(function TerminalPane({
  pane,
  isActive,
  isFullscreen,
  sessions,
  canSplit,
  canClose,
  onSessionSelect,
  onSplit,
  onClose,
  onFocus,
  onFullscreen,
  showPreview,
  onMinimizeMainTerminal,
  keybarOpen,
  viewportHeight,
  onUrlDetected,
  fontSize,
  webglEnabled,
  sessionActivity,
  projectInfo,
  sessionAiTypes,
  customAiProviders = [],
  onSetSessionAiType,
  onAddCustomAiProvider,
  onCwdChange,
  onSessionBusyChange,
  currentDesktopId,
  fitSignal
}) {
  const paneRef = useRef(null);
  const imageInputRef = useRef(null);
  const menuRef = useRef(null);
  const [isDragOver, setIsDragOver] = useState(false);
  const [isHeaderDragging, setIsHeaderDragging] = useState(false);
  const [showSessionMenu, setShowSessionMenu] = useState(false);
  const [connectionState, setConnectionState] = useState('connecting');
  const [currentCwd, setCurrentCwd] = useState(null);
  const [refreshToken, setRefreshToken] = useState(0);
  const [isSessionBusy, setIsSessionBusy] = useState(false);
  const [launchQueued, setLaunchQueued] = useState(false);
  const [composerValue, setComposerValue] = useState('');
  const [composerAttachments, setComposerAttachments] = useState([]);
  const [viewModeNotice, setViewModeNotice] = useState('');
  const [isNoticePersistent, setIsNoticePersistent] = useState(false);
  const [terminalPreview, setTerminalPreview] = useState('');
  const [terminalScreenSnapshot, setTerminalScreenSnapshot] = useState('');
  const [interactivePromptEvent, setInteractivePromptEvent] = useState(null);
  const [isTerminalPanelOpen, setIsTerminalPanelOpen] = useState(false);
  const [gitBranchInfo, setGitBranchInfo] = useState(null);
  const [isLoadingGitBranches, setIsLoadingGitBranches] = useState(false);
  const [isSwitchingGitBranch, setIsSwitchingGitBranch] = useState(false);
  const conversationFallbackRef = useRef(false);
  const interactivePromptRef = useRef(null);
  const outputProbeRef = useRef('');
  const hasConnectedOnceRef = useRef(false);
  const handleToggleTerminalPanel = useCallback(() => {
    setIsTerminalPanelOpen((isOpen) => {
      const next = !isOpen;
      if (next) {
        conversationFallbackRef.current = false;
        setIsNoticePersistent(false);
        setViewModeNotice('');
      }
      return next;
    });
  }, []);

  const { listSessionGitBranches, checkoutSessionGitBranch } = useTerminalSession();

  const selectableSessions = useMemo(
    () => sessions.filter((session) => !session.thread?.archived),
    [sessions]
  );
  const currentSession = selectableSessions.find(s => s.id === pane.sessionId);
  const currentAiType = sessionAiTypes?.[pane.sessionId] ?? null;
  const currentAiCapabilities = getAiCapabilities(currentAiType, customAiProviders);
  const launchCommand = getAiInitialCommand(currentAiType, customAiProviders);
  const aiOptions = getAiTypeOptions(customAiProviders);
  const rawTopic = currentSession?.thread?.topic || null;
  const useTopic = isReasonablePaneSummary(rawTopic, currentSession?.thread?.topicAutoGenerated);
  const paneSummaryText = (useTopic ? rawTopic : null) || currentSession?.title || null;
  const currentSessionLabel = getPaneSessionLabel(currentSession);
  const runtimeInfo = useMemo(
    () => parseTerminalRuntimeInfo(terminalScreenSnapshot || terminalPreview, currentAiType),
    [currentAiType, terminalPreview, terminalScreenSnapshot]
  );
  const showSessionSelector = canClose && selectableSessions.length > 0;
  // Detect if session uses structured mode (ss- prefix)
  const isStructuredSession = Boolean(pane.sessionId && pane.sessionId.startsWith('ss-'));
  const useTerminalFirstLayout = !isStructuredSession;

  const {
    turns,
    isLoading: isConversationHistoryLoading,
    isSendReady,
    handleTurn,
    handleRegisterSendText,
    handleChatSend,
    handleRawSend,
  } = useMobileChatTurns({
    sessionId: pane.sessionId ?? null,
    chatMode: Boolean(pane.sessionId) && !isStructuredSession,
  });

  const {
    messages: structuredMessages,
    currentToolCalls: structuredToolCalls,
    pendingApproval,
    isStreaming: structuredIsStreaming,
    connectionState: structuredConnectionState,
    sendMessage: structuredSendMessage,
    interrupt: structuredInterrupt,
    approve: structuredApprove,
  } = useStructuredSession({
    sessionId: isStructuredSession ? pane.sessionId : null,
    active: isStructuredSession,
  });

  useEffect(() => {
    if (!viewModeNotice || isNoticePersistent) return;
    const timer = setTimeout(() => setViewModeNotice(''), 5000);
    return () => clearTimeout(timer);
  }, [viewModeNotice, isNoticePersistent]);

  useEffect(() => {
    setIsSessionBusy(false);
    setIsTerminalPanelOpen(false);
    setConnectionState('connecting');
    setLaunchQueued(false);
    setComposerValue('');
    setComposerAttachments([]);
    setTerminalPreview('');
    setTerminalScreenSnapshot('');
    setInteractivePromptEvent(null);
    setViewModeNotice('');
    setIsNoticePersistent(false);
    setGitBranchInfo(null);
    setIsLoadingGitBranches(false);
    setIsSwitchingGitBranch(false);
    conversationFallbackRef.current = false;
    interactivePromptRef.current = null;
    outputProbeRef.current = '';
    hasConnectedOnceRef.current = false;
  }, [pane.sessionId]);

  useEffect(() => {
    if (!isSendReady || !launchQueued) return;
    setLaunchQueued(false);
    setIsNoticePersistent(false);
    setViewModeNotice('');
  }, [isSendReady, launchQueued]);

  // Close session menu on outside click
  useEffect(() => {
    if (!showSessionMenu) return;
    const handleClickOutside = (e) => {
      if (menuRef.current && !menuRef.current.contains(e.target)) {
        setShowSessionMenu(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [showSessionMenu]);

  useEffect(() => {
    if (!pane.sessionId) return;

    let cancelled = false;
    setIsLoadingGitBranches(true);
    listSessionGitBranches(pane.sessionId)
      .then((data) => {
        if (!cancelled) {
          setGitBranchInfo(data);
        }
      })
      .finally(() => {
        if (!cancelled) {
          setIsLoadingGitBranches(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [listSessionGitBranches, pane.sessionId, projectInfo?.gitBranch]);

  const handleSelectGitBranch = useCallback(async (nextBranch) => {
    if (!pane.sessionId || !nextBranch || nextBranch === gitBranchInfo?.currentBranch) return;
    setIsSwitchingGitBranch(true);
    const result = await checkoutSessionGitBranch(pane.sessionId, nextBranch);
    if (result) {
      setGitBranchInfo(result);
    }
    setIsSwitchingGitBranch(false);
  }, [checkoutSessionGitBranch, gitBranchInfo?.currentBranch, pane.sessionId]);

  const handlePaneClick = (e) => {
    if (!e.target.closest('.ph-controls') && !e.target.closest('.ph-session-menu')) {
      onFocus(pane.id);
    }
  };

  const handleDragOver = useCallback((e) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
    setIsDragOver(true);
  }, []);

  const handleDragLeave = useCallback(() => {
    setIsDragOver(false);
  }, []);

  const handleDrop = useCallback((e) => {
    e.preventDefault();
    setIsDragOver(false);
    const sessionId = e.dataTransfer.getData('session-id');
    if (sessionId) {
      onSessionSelect(pane.id, sessionId);
    }
  }, [pane.id, onSessionSelect]);

  const handleSessionClick = useCallback((e) => {
    e.stopPropagation();
    setShowSessionMenu(prev => !prev);
  }, []);

  const handleSessionSelect = useCallback((sessionId) => {
    onSessionSelect(pane.id, sessionId);
    setShowSessionMenu(false);
  }, [pane.id, onSessionSelect]);

  const handleImageUpload = useCallback(() => {
    imageInputRef.current?.click();
  }, []);

  const handleConnectionChange = useCallback((connected) => {
    if (connected) {
      hasConnectedOnceRef.current = true;
      setConnectionState('online');
      return;
    }
    setConnectionState(hasConnectedOnceRef.current ? 'offline' : 'connecting');
  }, []);

  const handleActivityChange = useCallback((isBusy) => {
    setIsSessionBusy(Boolean(isBusy));
    onSessionBusyChange?.(pane.sessionId, isBusy);
  }, [onSessionBusyChange, pane.sessionId]);

  const handleOutputChunk = useCallback((chunk) => {
    if (typeof chunk !== 'string' || chunk.length === 0) return;
    const chunkLooksInteractive = shouldFallbackToTerminalView(chunk);

    if (interactivePromptRef.current) {
      const normalizedChunk = chunk.toLowerCase();
      const stillLooksInteractive =
        /\[[yYnN]\/[yYnN]\]/.test(chunk)
        || normalizedChunk.includes('enter to confirm')
        || normalizedChunk.includes('esc to cancel')
        || normalizedChunk.includes('tab to cycle');
      if (!stillLooksInteractive) {
        interactivePromptRef.current = null;
        setInteractivePromptEvent(null);
        conversationFallbackRef.current = false;
        setIsNoticePersistent(false);
        setViewModeNotice('');
      }
    }

    if (conversationFallbackRef.current && !interactivePromptRef.current && !chunkLooksInteractive) {
      conversationFallbackRef.current = false;
      outputProbeRef.current = '';
      setIsNoticePersistent(false);
      setViewModeNotice('');
    }

    const previewLines = extractTerminalPreviewLines(chunk);
    if (previewLines.length > 0) {
      setTerminalPreview((previous) => {
        const prevLines = previous ? previous.split('\n') : [];
        const next = [...prevLines, ...previewLines].slice(-8).join('\n');
        return next === previous ? previous : next;
      });
    }

    if (conversationFallbackRef.current) return;

    outputProbeRef.current = `${outputProbeRef.current}${chunk}`.slice(-4000);
    if (!shouldFallbackToTerminalView(outputProbeRef.current)) return;

    conversationFallbackRef.current = true;
    setIsNoticePersistent(false);
    setViewModeNotice('');
  }, [currentAiCapabilities.prefersStructuredUi]);

  const handleCliEvent = useCallback((event) => {
    if (!event || typeof event !== 'object') return;

    if (event.type === 'prompt_required') {
      interactivePromptRef.current = event;
      setInteractivePromptEvent(event);
      setIsNoticePersistent(false);
      setViewModeNotice('');
      return;
    }

    if (event.type === 'assistant_turn' || event.type === 'user_turn') {
      interactivePromptRef.current = null;
      setInteractivePromptEvent(null);
      conversationFallbackRef.current = false;
      setIsNoticePersistent(false);
      setViewModeNotice('');
    }
  }, []);

  const handleScreenSnapshot = useCallback((snapshot) => {
    const next = typeof snapshot?.text === 'string' ? snapshot.text : '';
    setTerminalScreenSnapshot((previous) => (previous === next ? previous : next));
  }, []);

  const handleOpenTerminalPanel = useCallback(() => {
    setIsTerminalPanelOpen(true);
    conversationFallbackRef.current = false;
    setIsNoticePersistent(false);
    setViewModeNotice('');
  }, []);

  const launchAiType = useCallback((aiTypeToLaunch, commandOverride = null) => {
    const nextLaunchCommand = commandOverride || getAiInitialCommand(aiTypeToLaunch, customAiProviders);
    if (!nextLaunchCommand) return;
    interactivePromptRef.current = null;
    setInteractivePromptEvent(null);
    const result = handleChatSend(nextLaunchCommand);
    if (result?.queued) {
      setLaunchQueued(true);
      setIsNoticePersistent(false);
      setViewModeNotice('Terminal is still connecting. Launch command queued.');
      return;
    }
    setLaunchQueued(false);
    setIsNoticePersistent(false);
    setViewModeNotice('');
  }, [customAiProviders, handleChatSend]);

  const handleLaunchAgent = useCallback(() => {
    launchAiType(currentAiType);
  }, [currentAiType, launchAiType]);

  const handleComposerSubmit = useCallback((text) => {
    if (!pane.sessionId) return;
    const trimmed = typeof text === 'string' ? text.trim() : '';
    const attachmentPaths = composerAttachments
      .map((attachment) => attachment?.path)
      .filter((path) => typeof path === 'string' && path.trim());
    if (!trimmed && attachmentPaths.length === 0) return;

    const payload = [attachmentPaths.join(' '), trimmed].filter(Boolean).join(' ').trim();
    if (!payload) return;

    const result = handleChatSend(payload);
    setComposerValue('');
    setComposerAttachments([]);

    if (result?.queued) {
      setIsNoticePersistent(false);
      setViewModeNotice('Terminal is still connecting. Command queued.');
    } else if (viewModeNotice) {
      setIsNoticePersistent(false);
      setViewModeNotice('');
    }
  }, [composerAttachments, handleChatSend, pane.sessionId, viewModeNotice]);

  const handleComposerAttachmentAdd = useCallback((attachment) => {
    if (!attachment?.path) return;
    setComposerAttachments((current) => {
      if (current.some((item) => item.path === attachment.path)) return current;
      return [...current, attachment];
    });
  }, []);

  const handleComposerAttachmentRemove = useCallback((pathToRemove) => {
    setComposerAttachments((current) => current.filter((attachment) => attachment.path !== pathToRemove));
  }, []);

  const handleSelectAiType = useCallback((nextAiType) => {
    if (!pane.sessionId) return;
    onSetSessionAiType?.(pane.sessionId, nextAiType);
    if (nextAiType) {
      launchAiType(nextAiType);
    }
  }, [launchAiType, onSetSessionAiType, pane.sessionId]);

  const handleAddCustomAiCommand = useCallback((label, command) => {
    if (!pane.sessionId) return;
    const provider = onAddCustomAiProvider?.(label, command);
    if (!provider?.id) return;
    onSetSessionAiType?.(pane.sessionId, provider.id);
    launchAiType(provider.id, provider.initialCommand);
  }, [launchAiType, onAddCustomAiProvider, onSetSessionAiType, pane.sessionId]);

  const handleCwdChange = useCallback((cwd) => {
    setCurrentCwd(cwd);
    onCwdChange?.(cwd);
  }, [onCwdChange]);

  const handleRefreshTerminal = useCallback(() => {
    setRefreshToken((value) => value + 1);
  }, []);

  const handleHeaderDragStart = useCallback((e) => {
    if (!pane.sessionId) return;
    e.dataTransfer.setData('pane-drag', JSON.stringify({
      paneId: pane.id,
      sessionId: pane.sessionId,
      fromDesktopId: currentDesktopId
    }));
    e.dataTransfer.effectAllowed = 'move';
    setIsHeaderDragging(true);
  }, [pane.id, pane.sessionId, currentDesktopId]);

  const handleHeaderDragEnd = useCallback(() => {
    setIsHeaderDragging(false);
  }, []);

  return (
    <div
      ref={paneRef}
      className={`split-terminal-pane ${isActive ? 'active' : ''} ${isFullscreen ? 'fullscreen' : ''} ${isDragOver ? 'drag-over' : ''}${sessionAiTypes?.[pane.sessionId] ? ` pane-ai-${sessionAiTypes[pane.sessionId]}` : ''}`}
      onClick={handlePaneClick}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      <div
        className={`ph-bar${isHeaderDragging ? ' is-dragging-pane' : ''}`}
        draggable={Boolean(pane.sessionId)}
        onDragStart={handleHeaderDragStart}
        onDragEnd={handleHeaderDragEnd}
      >
        <div className="ph-left">
          {/* Session selector - only in split mode with multiple sessions */}
          {showSessionSelector && (
            <div className="ph-session" ref={menuRef}>
              <button
                type="button"
                className="ph-session-btn"
                onClick={handleSessionClick}
                aria-label={currentSessionLabel}
              >
                <span className="ph-session-dot" />
                <span className="ph-session-name">
                  {currentSessionLabel}
                </span>
                <svg className="ph-session-chevron" width="8" height="8" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </button>

              {showSessionMenu && (
                <div className="ph-session-menu">
                  <div className="ph-menu-label">Switch session</div>
                  {selectableSessions.map(session => {
                    const hasUnread = sessionActivity?.[session.id]?.hasUnread;
                    const isCurrentSession = session.id === pane.sessionId;
                    const sessionLabel = getPaneSessionLabel(session);
                    return (
                      <button
                        key={session.id}
                        type="button"
                        className={`ph-menu-item ${isCurrentSession ? 'active' : ''}`}
                        onClick={() => handleSessionSelect(session.id)}
                      >
                        {hasUnread && <span className="ph-menu-dot" />}
                        <span className="ph-menu-title">{sessionLabel}</span>
                        {isCurrentSession && (
                          <svg className="ph-menu-check" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                            <polyline points="20 6 9 17 4 12" />
                          </svg>
                        )}
                      </button>
                    );
                  })}
                  {selectableSessions.length === 0 && (
                    <div className="ph-menu-empty">No sessions available</div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* Minimal Session Topic Summary */}
          {paneSummaryText && (
            <>
              {showSessionSelector && <span className="ph-topic-sep">/</span>}
              <span className="ph-topic" title={paneSummaryText} style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 0.4 }}>
                  <polyline points="4 17 10 11 4 5" />
                  <line x1="12" y1="19" x2="20" y2="19" />
                </svg>
                {paneSummaryText.toLowerCase()}
              </span>
            </>
          )}
        </div>

        <div className="ph-controls">
          {/* Reconnect */}
          <button
            className="ph-btn"
            onClick={(e) => { e.stopPropagation(); handleRefreshTerminal(); }}
            title="Reconnect terminal"
          >
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="23 4 23 10 17 10" />
              <path d="M20.49 15a9 9 0 1 1 2.13-9" />
            </svg>
          </button>

          {/* Split buttons */}
          {canSplit && !isFullscreen && (
            <>

              <button
                className="ph-btn"
                onClick={(e) => { e.stopPropagation(); onSplit(pane.id, 'horizontal'); }}
                title="Split horizontally"
              >
                <svg width="13" height="13" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <rect x="1" y="2" width="5" height="10" rx="1" />
                  <rect x="8" y="2" width="5" height="10" rx="1" />
                </svg>
              </button>
              <button
                className="ph-btn"
                onClick={(e) => { e.stopPropagation(); onSplit(pane.id, 'vertical'); }}
                title="Split vertically"
              >
                <svg width="13" height="13" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <rect x="2" y="1" width="10" height="5" rx="1" />
                  <rect x="2" y="8" width="10" height="5" rx="1" />
                </svg>
              </button>
            </>
          )}

          {/* Minimize to show preview */}
          {showPreview && !isFullscreen && onMinimizeMainTerminal && (
            <>

              <button
                className="ph-btn"
                onClick={(e) => { e.stopPropagation(); onMinimizeMainTerminal(); }}
                title="Minimize terminal (show browser)"
              >
                <svg width="13" height="13" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                  <rect x="1" y="2" width="6" height="10" rx="1" />
                  <polyline points="8 5 11 7 8 9" />
                </svg>
              </button>
            </>
          )}

          {/* Fullscreen */}
          <span className="ph-divider" />
          <button
            className="ph-btn"
            onClick={(e) => { e.stopPropagation(); onFullscreen(pane.id); }}
            title={isFullscreen ? 'Exit fullscreen' : 'Fullscreen'}
          >
            {isFullscreen ? (
              <svg width="13" height="13" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5">
                <polyline points="4 10 1 10 1 13" />
                <polyline points="10 4 13 4 13 1" />
                <line x1="1" y1="13" x2="5" y2="9" />
                <line x1="9" y1="5" x2="13" y2="1" />
              </svg>
            ) : (
              <svg width="13" height="13" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5">
                <polyline points="10 1 13 1 13 4" />
                <polyline points="4 13 1 13 1 10" />
                <line x1="13" y1="1" x2="9" y2="5" />
                <line x1="1" y1="13" x2="5" y2="9" />
              </svg>
            )}
          </button>

          {/* Close pane */}
          {canClose && !isFullscreen && (
            <button
              className="ph-btn ph-btn-close"
              onClick={(e) => { e.stopPropagation(); onClose(pane.id); }}
              title="Close pane"
            >
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </button>
          )}
        </div>
      </div>

      <div className="pane-content">
        {pane.sessionId ? (
          <div className={`terminal-with-status${useTerminalFirstLayout ? ' terminal-first' : ''}`}>
            <div className={`desktop-terminal-stack${isTerminalPanelOpen ? ' terminal-panel-open' : ''}${useTerminalFirstLayout ? ' terminal-first' : ''}`}>
              {/* CliActivityStrip removed — interactive prompts handled in terminal directly */}
              {!useTerminalFirstLayout && (
                <div className="desktop-conversation-surface">
                  <DesktopConversationView
                    turns={turns}
                    isStreaming={structuredIsStreaming}
                    isLoadingHistory={isConversationHistoryLoading}
                    onSend={structuredSendMessage}
                    onSendRaw={handleRawSend}
                    onInterrupt={structuredInterrupt}
                    onImageUpload={handleImageUpload}
                    sessionId={pane.sessionId}
                    aiType={currentAiType}
                    connectionState={structuredConnectionState}
                    isSendReady
                    terminalPreview={terminalPreview}
                    terminalScreenSnapshot={terminalScreenSnapshot}
                    launchCommand=""
                    launchQueued={launchQueued}
                    onLaunchAgent={handleLaunchAgent}
                    onOpenTerminal={handleOpenTerminalPanel}
                    conversationNotice={viewModeNotice}
                    showTerminalMirror={Boolean(interactivePromptEvent) || isNoticePersistent}
                    interactivePromptEvent={interactivePromptEvent}
                    mode="structured"
                    structuredMessages={structuredMessages}
                    structuredToolCalls={structuredToolCalls}
                    pendingApproval={pendingApproval}
                    onApprove={structuredApprove}
                  />
                </div>
              )}

              <div
                className={`desktop-terminal-runtime${useTerminalFirstLayout || isTerminalPanelOpen ? ' inline-panel-open' : ' is-hidden'}${useTerminalFirstLayout ? ' terminal-first' : ''}`}
                aria-hidden={!useTerminalFirstLayout && !isTerminalPanelOpen ? 'true' : undefined}
              >
                <TerminalChat
                  key={`${pane.sessionId}-${refreshToken}`}
                  surface="desktop"
                  sessionId={pane.sessionId}
                  keybarOpen={keybarOpen}
                  viewportHeight={viewportHeight}
                  onUrlDetected={onUrlDetected}
                  fontSize={fontSize}
                  webglEnabled={webglEnabled}
                  usesTmux={currentSession?.usesTmux}
                  viewMode="terminal"
                  isPrimary={isActive}
                  fitSignal={fitSignal}
                  onRegisterImageUpload={(trigger) => { imageInputRef.current = { click: trigger }; }}
                  onConnectionChange={handleConnectionChange}
                  onCwdChange={handleCwdChange}
                  onActivityChange={handleActivityChange}
                  onOutputChunk={handleOutputChunk}
                  onScreenSnapshot={handleScreenSnapshot}
                  onCliEvent={handleCliEvent}
                  onRegisterSendText={handleRegisterSendText}
                  onTurn={handleTurn}
                />
              </div>
            </div>
            <DesktopStatusBar
              sessionId={pane.sessionId}
              sessionTitle={currentSession?.title}
              cwd={currentCwd || projectInfo?.cwd}
              gitBranch={projectInfo?.gitBranch}
              onImageUpload={handleImageUpload}
              isTerminalPanelOpen={isTerminalPanelOpen}
              showTerminalToggle={!useTerminalFirstLayout}
              onToggleTerminalPanel={useTerminalFirstLayout ? undefined : handleToggleTerminalPanel}
              connectionState={connectionState}
              aiType={currentAiType}
              aiOptions={aiOptions}
                onSelectAiType={handleSelectAiType}
                onAddCustomAiCommand={handleAddCustomAiCommand}
                onLaunchAi={handleLaunchAgent}
                composerValue={composerValue}
                composerAttachments={composerAttachments}
                onComposerChange={setComposerValue}
                onComposerSubmit={handleComposerSubmit}
                onComposerAttachmentAdd={handleComposerAttachmentAdd}
                onComposerAttachmentRemove={handleComposerAttachmentRemove}
              composerPlaceholder="Ask V4 anything"
              composerDisabled={!pane.sessionId}
              runtimeInfo={runtimeInfo}
              gitBranches={gitBranchInfo?.branches || []}
              currentGitBranch={gitBranchInfo?.currentBranch || projectInfo?.gitBranch || null}
              isLoadingGitBranches={isLoadingGitBranches}
              isSwitchingGitBranch={isSwitchingGitBranch}
              onSelectGitBranch={handleSelectGitBranch}
              />
          </div>
        ) : (
          <div className="pane-empty pane-home">
            <div className="pane-home-copy">
              <span className="pane-home-kicker">Workspace</span>
              <h2>Select a terminal to get started</h2>
              <p>Pick an active thread from the sidebar, or create a new terminal to start sending prompts and commands.</p>
            </div>
          </div>
        )}
      </div>

      <style>{`
        /* ── Pane header bar ── */
        .ph-bar {
          display: flex;
          align-items: center;
          justify-content: space-between;
          height: 36px;
          padding: 0 6px 0 10px;
          background: var(--terminal-chrome-bg, #17191c);
          border-bottom: none;
          flex-shrink: 0;
        }

        .ph-bar[draggable=true] { cursor: grab; }
        .ph-bar.is-dragging-pane { opacity: 0.5; cursor: grabbing; }

        .ph-left {
          display: flex;
          align-items: center;
          min-width: 0;
          flex: 1;
        }

        /* ── Topic summary ── */
        .ph-topic-sep {
          color: var(--text-muted);
          opacity: 0.5;
          padding: 0 6px;
          flex-shrink: 0;
          font-size: 12px;
        }

        .ph-topic {
          font-size: 11px;
          color: var(--text-muted);
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
          max-width: 220px;
          flex-shrink: 1;
        }

        /* ── Session selector ── */
        .ph-session {
          position: relative;
        }

        .ph-session-btn {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 4px 8px 4px 8px;
          background: var(--bg-elevated);
          border: 1px solid var(--border-subtle);
          border-radius: var(--radius-sm, 4px);
          color: var(--text-secondary);
          font-size: 12px;
          font-weight: 500;
          cursor: pointer;
          transition: all var(--transition-fast, 0.15s ease);
        }

        .ph-session-btn:hover {
          border-color: var(--accent-primary);
          color: var(--accent-primary);
        }

        .ph-session-dot {
          width: 6px;
          height: 6px;
          border-radius: 50%;
          background: var(--accent-primary);
          opacity: 0.7;
          flex-shrink: 0;
        }

        .ph-session-name {
          max-width: 140px;
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
        }

        .ph-session-chevron {
          opacity: 0.5;
          flex-shrink: 0;
        }

        .pane-home {
          display: flex;
          align-items: center;
          justify-content: center;
          min-height: 100%;
          padding: 32px;
          background:
            radial-gradient(circle at top, rgba(56, 189, 248, 0.08), transparent 32%),
            linear-gradient(180deg, rgba(255, 255, 255, 0.015), rgba(255, 255, 255, 0));
        }

        .pane-home-copy {
          max-width: 420px;
          text-align: center;
        }

        .pane-home-kicker {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          padding: 4px 10px;
          border-radius: 999px;
          border: 1px solid rgba(56, 189, 248, 0.18);
          background: rgba(56, 189, 248, 0.08);
          color: rgba(147, 197, 253, 0.88);
          font-size: 11px;
          font-weight: 600;
          letter-spacing: 0.06em;
          text-transform: uppercase;
          margin-bottom: 14px;
        }

        .pane-home h2 {
          margin: 0 0 10px;
          font-size: 24px;
          line-height: 1.1;
          color: var(--text-primary);
        }

        .pane-home p {
          margin: 0;
          color: var(--text-secondary);
          font-size: 14px;
          line-height: 1.6;
        }

        /* ── Session dropdown menu ── */
        .ph-session-menu {
          position: absolute;
          top: calc(100% + 4px);
          left: 0;
          min-width: 200px;
          max-height: 260px;
          overflow-y: auto;
          background: var(--bg-elevated);
          border: 1px solid var(--border-default);
          border-radius: var(--radius-md, 8px);
          box-shadow: var(--shadow-lg, 0 8px 24px rgba(0, 0, 0, 0.5));
          z-index: 1000;
          padding: 4px;
        }

        .ph-menu-label {
          padding: 6px 10px 4px;
          font-size: 10px;
          font-weight: 650;
          text-transform: uppercase;
          letter-spacing: 0.4px;
          color: var(--text-muted);
        }

        .ph-menu-item {
          display: flex;
          align-items: center;
          gap: 8px;
          width: 100%;
          padding: 6px 10px;
          background: transparent;
          border: none;
          border-radius: var(--radius-sm, 4px);
          color: var(--text-secondary);
          font-size: 12px;
          text-align: left;
          cursor: pointer;
          transition: all var(--transition-fast, 0.15s ease);
        }

        .ph-menu-item:hover {
          background: var(--bg-surface);
          color: var(--text-primary);
        }

        .ph-menu-item.active {
          background: var(--accent-primary-dim);
          color: var(--accent-primary);
        }

        .ph-menu-dot {
          width: 5px;
          height: 5px;
          border-radius: 50%;
          background: var(--accent-primary);
          flex-shrink: 0;
        }

        .ph-menu-title {
          flex: 1;
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
        }

        .ph-menu-check {
          flex-shrink: 0;
          opacity: 0.8;
          color: var(--accent-primary);
        }

        .ph-menu-empty {
          padding: 12px 10px;
          font-size: 11px;
          color: var(--text-muted);
          text-align: center;
        }

        /* ── Control buttons ── */
        .ph-controls {
          display: flex;
          align-items: center;
          gap: 4px;
          flex-shrink: 0;
        }

        .ph-btn {
          background: var(--bg-elevated);
          border: 1px solid var(--border-subtle);
          border-radius: var(--radius-sm, 4px);
          padding: 5px;
          color: var(--text-muted);
          cursor: pointer;
          transition: all var(--transition-fast, 0.15s ease);
          display: flex;
          align-items: center;
          justify-content: center;
          line-height: 1;
        }

        .ph-btn svg {
          display: block;
        }

        .ph-btn:hover {
          background: var(--bg-surface);
          border-color: var(--accent-primary);
          color: var(--accent-primary);
        }

        .ph-btn-close:hover {
          background: rgba(244, 63, 94, 0.1);
          border-color: var(--error);
          color: var(--error);
        }

        @media (max-width: 768px) {
          .ph-btn {
            min-width: 44px;
            min-height: 44px;
            padding: 10px;
          }
        }
      `}</style>
    </div>
  );
});
