import { z } from 'zod';

export const terminalCreateRequestSchema = z.object({
  cwd: z.string().optional(),
  cols: z.number().int().positive().max(500).optional(),
  rows: z.number().int().positive().max(500).optional(),
  title: z.string().min(1).max(80).optional(),
  shell: z.string().min(1).optional(),
  shellArgs: z.array(z.string().max(256)).max(20).optional(),
  shellProfile: z.enum(['system', 'cmd', 'powershell', 'pwsh', 'bash', 'zsh', 'sh', 'claude']).optional(),
  fidelityMode: z.enum(['balanced', 'native']).optional(),
  initialCommand: z.string().max(1000).optional()
});

export type TerminalCreateRequestBody = z.infer<typeof terminalCreateRequestSchema>;

export const terminalOpenNativeRequestSchema = z.object({
  launcher: z.enum(['system', 'wt', 'cmd', 'powershell', 'pwsh', 'terminal', 'x-terminal-emulator']).optional()
});

export type TerminalOpenNativeRequestBody = z.infer<typeof terminalOpenNativeRequestSchema>;

// Maximum input size: 1MB (reasonable limit for terminal input while allowing large pastes)
const MAX_TERMINAL_INPUT_SIZE = 1024 * 1024;

export const terminalInputRequestSchema = z.object({
  command: z
    .string({ error: 'command must be a string' })
    .min(1, 'command cannot be empty')
    .max(MAX_TERMINAL_INPUT_SIZE, 'command exceeds maximum allowed size')
});

export type TerminalInputRequestBody = z.infer<typeof terminalInputRequestSchema>;

export const terminalResizeRequestSchema = z.object({
  cols: z.number().positive().max(500).transform(Math.round),
  rows: z.number().positive().max(500).transform(Math.round)
});

export type TerminalResizeRequestBody = z.infer<typeof terminalResizeRequestSchema>;

export const terminalRenameRequestSchema = z.object({
  title: z.string().trim().min(1, 'title cannot be empty').max(60, 'title too long')
});

export type TerminalRenameRequestBody = z.infer<typeof terminalRenameRequestSchema>;

export const bookmarkCreateRequestSchema = z.object({
  name: z
    .string({ error: 'name must be a string' })
    .min(1, 'name cannot be empty')
    .max(100, 'name too long'),
  command: z
    .string({ error: 'command must be a string' })
    .min(1, 'command cannot be empty')
    .max(1000, 'command too long'),
  category: z
    .string({ error: 'category must be a string' })
    .min(1, 'category cannot be empty')
    .max(50, 'category too long')
});

export type BookmarkCreateRequestBody = z.infer<typeof bookmarkCreateRequestSchema>;

export const bookmarkUpdateRequestSchema = z.object({
  name: z.string().min(1).max(100).optional(),
  command: z.string().min(1).max(1000).optional(),
  category: z.string().min(1).max(50).optional()
});

export type BookmarkUpdateRequestBody = z.infer<typeof bookmarkUpdateRequestSchema>;

// File Manager schemas
export const fileListQuerySchema = z.object({
  path: z.string().optional() // defaults to ~
});

export type FileListQuery = z.infer<typeof fileListQuerySchema>;

export const fileMkdirRequestSchema = z.object({
  path: z.string().min(1).max(4096) // full path including new folder name
});

export type FileMkdirRequestBody = z.infer<typeof fileMkdirRequestSchema>;

export const fileDeleteRequestSchema = z.object({
  path: z.string().min(1).max(4096)
});

export type FileDeleteRequestBody = z.infer<typeof fileDeleteRequestSchema>;

export const fileRenameRequestSchema = z.object({
  oldPath: z.string().min(1).max(4096),
  newPath: z.string().min(1).max(4096)
});

export type FileRenameRequestBody = z.infer<typeof fileRenameRequestSchema>;

export const fileUnzipRequestSchema = z.object({
  zipPath: z.string().min(1).max(4096),
  extractTo: z.string().max(4096).optional() // defaults to same directory as zip
});

export type FileUnzipRequestBody = z.infer<typeof fileUnzipRequestSchema>;

// Note schemas
export const noteCreateRequestSchema = z.object({
  title: z
    .string({ error: 'title must be a string' })
    .min(1, 'title cannot be empty')
    .max(200, 'title too long'),
  content: z
    .string({ error: 'content must be a string' })
    .max(50000, 'content too long'),
  category: z
    .string({ error: 'category must be a string' })
    .min(1, 'category cannot be empty')
    .max(50, 'category too long')
});

export type NoteCreateRequestBody = z.infer<typeof noteCreateRequestSchema>;

export const noteUpdateRequestSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  content: z.string().max(50000).optional(),
  category: z.string().min(1).max(50).optional()
});

export type NoteUpdateRequestBody = z.infer<typeof noteUpdateRequestSchema>;

// Thread metadata schemas
export const threadUpdateRequestSchema = z.object({
  topic: z.string().max(200).nullable().optional(),
  topicAutoGenerated: z.boolean().optional(),
  pinned: z.boolean().optional(),
  archived: z.boolean().optional(),
  projectPath: z.string().max(4096).nullable().optional()
});

export type ThreadUpdateRequestBody = z.infer<typeof threadUpdateRequestSchema>;

const previewRequestIdSchema = z.string().min(1).max(128).regex(/^[a-zA-Z0-9:_-]+$/);
const previewStorageKeySchema = z.string().min(1).max(256).regex(/^[a-zA-Z0-9_\-\.]+$/);
const previewStorageValueSchema = z.string().max(100_000);

export const previewEvaluateRequestSchema = z.object({
  expression: z.string().min(1).max(10_000),
  requestId: previewRequestIdSchema.optional()
});

export type PreviewEvaluateRequestBody = z.infer<typeof previewEvaluateRequestSchema>;

export const previewStorageUpdateRequestSchema = z.object({
  type: z.enum(['localStorage', 'sessionStorage', 'cookies']),
  operation: z.enum(['set', 'remove', 'clear', 'import']),
  key: previewStorageKeySchema.optional(),
  value: previewStorageValueSchema.optional(),
  entries: z.record(previewStorageKeySchema, previewStorageValueSchema).optional(),
  requestId: previewRequestIdSchema.optional()
}).superRefine((value, ctx) => {
  if (value.operation === 'set') {
    if (!value.key) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Missing key for set operation', path: ['key'] });
    }
    if (value.value === undefined) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Missing value for set operation', path: ['value'] });
    }
  }

  if (value.operation === 'remove' && !value.key) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Missing key for remove operation', path: ['key'] });
  }

  if (value.operation === 'import') {
    const entries = value.entries || {};
    const entryCount = Object.keys(entries).length;
    if (entryCount === 0) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Missing entries for import operation', path: ['entries'] });
    }
    if (entryCount > 1000) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Too many entries for import operation (max 1000)', path: ['entries'] });
    }
  }
});

export type PreviewStorageUpdateRequestBody = z.infer<typeof previewStorageUpdateRequestSchema>;

const previewPerformanceMetricDataSchema = z.object({}).catchall(z.unknown());

export const previewPerformanceMetricSchema = z.object({
  type: z.enum(['coreWebVitals', 'loadMetrics', 'runtimeMetrics']),
  timestamp: z.number().int().positive().optional(),
  data: previewPerformanceMetricDataSchema
});

export type PreviewPerformanceMetric = z.infer<typeof previewPerformanceMetricSchema>;

export const previewPerformanceIngestRequestSchema = z.object({
  metrics: z.array(previewPerformanceMetricSchema).min(1).max(500)
});

export type PreviewPerformanceIngestRequestBody = z.infer<typeof previewPerformanceIngestRequestSchema>;

export const previewWebSocketQuerySchema = z.object({
  connectionId: z.string().min(1).max(128).optional(),
  direction: z.enum(['sent', 'received']).optional()
});

export type PreviewWebSocketQuery = z.infer<typeof previewWebSocketQuerySchema>;
