import { getAiProvider } from './aiProviders';

function resolveSessionTimestamp(value) {
  const timestamp = Date.parse(value || '');
  return Number.isFinite(timestamp) ? timestamp : 0;
}

export function isStructuredSessionId(sessionId) {
  return typeof sessionId === 'string' && sessionId.startsWith('ss-');
}

export function buildStructuredSession(snapshot, metadata = {}) {
  const provider = getAiProvider(snapshot?.provider);
  const providerTitle = provider?.title ?? provider?.label ?? 'Structured session';
  const updatedAt = snapshot?.updatedAt || snapshot?.createdAt || new Date(0).toISOString();
  const snapshotThread = snapshot?.thread && typeof snapshot.thread === 'object'
    ? snapshot.thread
    : {};
  const threadMetadata = metadata?.thread && typeof metadata.thread === 'object'
    ? metadata.thread
    : {};
  const title = snapshot?.title || metadata?.title || providerTitle;
  const projectPath = snapshotThread.projectPath ?? threadMetadata.projectPath ?? snapshot?.cwd ?? '';
  const lastActivityAt = snapshotThread.lastActivityAt ?? threadMetadata.lastActivityAt ?? updatedAt;

  return {
    id: snapshot?.id ?? '',
    title,
    shell: snapshot?.provider ?? 'structured',
    aiType: snapshot?.provider ?? null,
    cwd: snapshot?.cwd ?? '',
    groupPath: projectPath,
    workspaceRoot: snapshot?.cwd ?? '',
    isActive: true,
    usesTmux: false,
    createdAt: snapshot?.createdAt ?? updatedAt,
    updatedAt,
    lastActivityAt,
    thread: {
      pinned: Boolean(snapshotThread.pinned ?? threadMetadata.pinned),
      archived: Boolean(snapshotThread.archived ?? threadMetadata.archived),
      topic: snapshotThread.topic ?? threadMetadata.topic ?? title,
      topicAutoGenerated: Boolean(snapshotThread.topicAutoGenerated ?? threadMetadata.topicAutoGenerated),
      projectPath,
      lastActivityAt,
    },
  };
}

export function mergeSessionCollections(
  terminalSessions = [],
  structuredSnapshots = [],
  structuredMetadata = {}
) {
  const mappedStructuredSessions = (Array.isArray(structuredSnapshots) ? structuredSnapshots : [])
    .map((snapshot) => buildStructuredSession(snapshot, structuredMetadata?.[snapshot?.id]));

  return [...(Array.isArray(terminalSessions) ? terminalSessions : []), ...mappedStructuredSessions]
    .sort((left, right) => {
      const leftTimestamp = resolveSessionTimestamp(left?.thread?.lastActivityAt || left?.updatedAt);
      const rightTimestamp = resolveSessionTimestamp(right?.thread?.lastActivityAt || right?.updatedAt);
      return rightTimestamp - leftTimestamp;
    });
}

export function normalizeStructuredMessageInput(data) {
  const payload = typeof data === 'string' ? data : String(data ?? '');
  const normalized = payload.replace(/\r\n/g, '\n').replace(/[\r\n]+$/g, '');
  return normalized.trim() ? normalized : '';
}
