import { act, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it, vi, beforeEach, afterEach } from 'vitest';
import { TerminalSessionProvider, useTerminalSession } from './TerminalSessionContext';

const { addRecentFolder, apiFetch, recentFolders } = vi.hoisted(() => ({
  addRecentFolder: vi.fn(),
  apiFetch: vi.fn(),
  recentFolders: [],
}));

vi.mock('./FolderContext', () => ({
  useFolders: () => ({
    recentFolders,
    addRecentFolder,
  })
}));

vi.mock('../utils/api', () => ({
  apiFetch,
  apiGet: vi.fn(),
}));

function TestConsumer() {
  const { loadingSessions, projectInfo, selectSession, sessions } = useTerminalSession();

  return (
    <>
      <span data-testid="loading-state">{loadingSessions ? 'loading' : 'idle'}</span>
      <span data-testid="project-cwd">{projectInfo?.cwd ?? 'none'}</span>
      <span data-testid="session-ids">{sessions.map((session) => session.id).join(',')}</span>
      <button type="button" onClick={() => selectSession('session-2')}>
        switch
      </button>
    </>
  );
}

function TestStructuredSessionConsumer() {
  const { sessions, closeSession } = useTerminalSession();

  return (
    <>
      <span data-testid="session-ids">{sessions.map((session) => session.id).join(',')}</span>
      <button type="button" onClick={() => closeSession('ss-structured')}>
        close structured
      </button>
    </>
  );
}

function TestStructuredLifecycleConsumer() {
  const { sessions, createStructuredSession, renameSession, updateThreadMetadata } = useTerminalSession();
  const structuredSession = sessions.find((session) => session.id.startsWith('ss-'));

  return (
    <>
      <span data-testid="session-ids">{sessions.map((session) => session.id).join(',')}</span>
      <span data-testid="structured-title">{structuredSession?.title ?? 'none'}</span>
      <span data-testid="structured-topic">{structuredSession?.thread?.topic ?? 'none'}</span>
      <span data-testid="structured-pinned">{String(Boolean(structuredSession?.thread?.pinned))}</span>
      <button
        type="button"
        onClick={() => createStructuredSession({ provider: 'claude', title: 'Agent thread' })}
      >
        create structured
      </button>
      <button
        type="button"
        onClick={() => renameSession('ss-structured', 'Renamed thread')}
      >
        rename structured
      </button>
      <button
        type="button"
        onClick={() => updateThreadMetadata('ss-structured', { topic: 'Review Rust rewrite', pinned: true })}
      >
        update structured thread
      </button>
    </>
  );
}

function TestGitBranchesConsumer() {
  const { listSessionGitBranches } = useTerminalSession();

  return (
    <button
      type="button"
      onClick={() => listSessionGitBranches('session-404')}
    >
      load branches
    </button>
  );
}

function TestThreadStateConsumer() {
  const { sessionsGroupedByProject, pinnedSessions, archivedSessions } = useTerminalSession();

  return (
    <>
      <span data-testid="thread-group-count">{String(sessionsGroupedByProject.length)}</span>
      <span data-testid="pinned-count">{String(pinnedSessions.length)}</span>
      <span data-testid="archived-count">{String(archivedSessions.length)}</span>
      <span data-testid="thread-session-ids">
        {sessionsGroupedByProject.flatMap((group) => group.sessions.map((session) => session.id)).join(',')}
      </span>
    </>
  );
}

function structuredSnapshot(overrides = {}) {
  return {
    id: 'ss-structured',
    cwd: 'C:\\repo',
    provider: 'claude',
    title: 'Structured session',
    createdAt: '2026-04-05T09:01:00.000Z',
    updatedAt: '2026-04-05T09:02:00.000Z',
    thread: {
      topic: 'Structured session',
      topicAutoGenerated: true,
      pinned: false,
      archived: false,
      projectPath: 'C:\\repo',
      lastActivityAt: '2026-04-05T09:02:00.000Z'
    },
    events: [],
    ...overrides
  };
}

describe('TerminalSessionContext', () => {
  beforeEach(() => {
    recentFolders.splice(0, recentFolders.length);
    apiFetch.mockImplementation(async (url) => {
      if (url === '/api/terminal') {
        return {
          ok: true,
          json: async () => ({
            sessions: [
              { id: 'session-1', isActive: true, title: 'Terminal 1' },
              { id: 'session-2', isActive: true, title: 'Terminal 2' }
            ]
          })
        };
      }

      if (url === '/api/structured/sessions') {
        return {
          ok: true,
          json: async () => []
        };
      }

      if (String(url).startsWith('/api/state')) {
        return {
          ok: true,
          json: async () => ({
            sessions: [
              { id: 'session-1', isActive: true, title: 'Terminal 1' },
              { id: 'session-2', isActive: true, title: 'Terminal 2' }
            ]
          })
        };
      }

      throw new Error(`Unexpected apiFetch call: ${url}`);
    });

    localStorage.clear();
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('does not trigger a full session reload when selecting another active session', async () => {
    render(
      <TerminalSessionProvider>
        <TestConsumer />
      </TerminalSessionProvider>
    );

    await waitFor(() => {
      expect(screen.getByTestId('loading-state')).toHaveTextContent('idle');
    });

    const terminalLoadCallsBeforeSwitch = apiFetch.mock.calls.filter(([url]) => url === '/api/terminal').length;

    await act(async () => {
      screen.getByRole('button', { name: 'switch' }).click();
    });

    await waitFor(() => {
      expect(screen.getByTestId('loading-state')).toHaveTextContent('idle');
    });

    const terminalLoadCallsAfterSwitch = apiFetch.mock.calls.filter(([url]) => url === '/api/terminal').length;
    expect(terminalLoadCallsAfterSwitch).toBe(terminalLoadCallsBeforeSwitch);
  });

  it('clears stale project info when the next selected session has no project metadata', async () => {
    localStorage.setItem('lastActiveSession', 'session-1');
    const hasFocusSpy = vi.spyOn(document, 'hasFocus').mockReturnValue(true);

    try {
      apiFetch.mockImplementation(async (url) => {
        if (url === '/api/terminal') {
          return {
            ok: true,
            json: async () => ({
              sessions: [
                { id: 'session-1', isActive: true, title: 'Terminal 1' },
                { id: 'session-2', isActive: true, title: 'Terminal 2' }
              ]
            })
          };
        }

        if (url === '/api/structured/sessions') {
          return {
            ok: true,
            json: async () => []
          };
        }

        if (url === '/api/state?sessionId=session-1') {
          return {
            ok: true,
            json: async () => ({
              sessions: [
                { id: 'session-1', isActive: true, title: 'Terminal 1' },
                { id: 'session-2', isActive: true, title: 'Terminal 2' }
              ],
              projectInfo: { cwd: 'C:\\repo\\one' }
            })
          };
        }

        if (url === '/api/state?sessionId=session-2') {
          return {
            ok: true,
            json: async () => ({
              sessions: [
                { id: 'session-1', isActive: true, title: 'Terminal 1' },
                { id: 'session-2', isActive: true, title: 'Terminal 2' }
              ],
              projectInfo: null
            })
          };
        }

        throw new Error(`Unexpected apiFetch call: ${url}`);
      });

      render(
        <TerminalSessionProvider>
          <TestConsumer />
        </TerminalSessionProvider>
      );

      await act(async () => {
        window.dispatchEvent(new Event('focus'));
      });

      await waitFor(() => {
        expect(screen.getByTestId('project-cwd')).toHaveTextContent('C:\\repo\\one');
      });

      await act(async () => {
        screen.getByRole('button', { name: 'switch' }).click();
      });

      await act(async () => {
        window.dispatchEvent(new Event('focus'));
      });

      await waitFor(() => {
        expect(screen.getByTestId('project-cwd')).toHaveTextContent('none');
      });
    } finally {
      hasFocusSpy.mockRestore();
    }
  });

  it('restores an inactive saved session only once during startup', async () => {
    localStorage.setItem('lastActiveSession', 'session-1');

    apiFetch.mockImplementation(async (url) => {
      if (url === '/api/terminal') {
        return {
          ok: true,
          json: async () => ({
            sessions: [
              { id: 'session-1', isActive: false, title: 'Terminal 1' }
            ]
          })
        };
      }

      if (url === '/api/structured/sessions') {
        return {
          ok: true,
          json: async () => []
        };
      }

      if (url === '/api/terminal/session-1/restore') {
        return {
          ok: true,
          json: async () => ({})
        };
      }

      if (String(url).startsWith('/api/state')) {
        return {
          ok: true,
          json: async () => ({
            sessions: [
              { id: 'session-1', isActive: true, title: 'Terminal 1' }
            ]
          })
        };
      }

      throw new Error(`Unexpected apiFetch call: ${url}`);
    });

    render(
      <TerminalSessionProvider>
        <TestConsumer />
      </TerminalSessionProvider>
    );

    await waitFor(() => {
      expect(screen.getByTestId('loading-state')).toHaveTextContent('idle');
    });

    await waitFor(() => {
      const restoreCalls = apiFetch.mock.calls.filter(([url]) => url === '/api/terminal/session-1/restore');
      expect(restoreCalls).toHaveLength(1);
    });
  });

  it('treats missing git branches as unavailable instead of logging an error', async () => {
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => {});

    apiFetch.mockImplementation(async (url) => {
      if (url === '/api/terminal') {
        return {
          ok: true,
          json: async () => ({ sessions: [] })
        };
      }

      if (String(url).startsWith('/api/state')) {
        return {
          ok: true,
          json: async () => ({ sessions: [] })
        };
      }

      if (url === '/api/terminal/session-404/git-branches') {
        return {
          ok: false,
          status: 404,
          json: async () => ({ error: 'Git branches not available for this terminal' })
        };
      }

      throw new Error(`Unexpected apiFetch call: ${url}`);
    });

    render(
      <TerminalSessionProvider>
        <TestGitBranchesConsumer />
      </TerminalSessionProvider>
    );

    await act(async () => {
      screen.getByRole('button', { name: 'load branches' }).click();
    });

    expect(errorSpy).not.toHaveBeenCalledWith('Failed to list git branches', expect.anything());
    errorSpy.mockRestore();
  });

  it('merges structured sessions into the session inventory', async () => {
    apiFetch.mockImplementation(async (url) => {
      if (url === '/api/terminal') {
        return {
          ok: true,
          json: async () => ({
            sessions: [
              { id: 'session-1', isActive: true, title: 'Terminal 1', updatedAt: '2026-04-05T09:00:00.000Z' }
            ]
          })
        };
      }

      if (url === '/api/structured/sessions') {
        return {
          ok: true,
          json: async () => ([
            structuredSnapshot()
          ])
        };
      }

      if (String(url).startsWith('/api/state')) {
        return {
          ok: true,
          json: async () => ({
            sessions: [
              { id: 'session-1', isActive: true, title: 'Terminal 1', updatedAt: '2026-04-05T09:00:00.000Z' }
            ]
          })
        };
      }

      throw new Error(`Unexpected apiFetch call: ${url}`);
    });

    render(
      <TerminalSessionProvider>
        <TestConsumer />
      </TerminalSessionProvider>
    );

    await waitFor(() => {
      expect(screen.getByTestId('session-ids')).toHaveTextContent('ss-structured,session-1');
    });
  });

  it('creates structured sessions through the structured API route with backend metadata', async () => {
    recentFolders.push('C:\\repo');
    let structuredSessions = [];

    apiFetch.mockImplementation(async (url, options = {}) => {
      if (url === '/api/terminal') {
        return {
          ok: true,
          json: async () => ({ sessions: [] })
        };
      }

      if (url === '/api/structured/sessions' && !options.method) {
        return {
          ok: true,
          json: async () => structuredSessions
        };
      }

      if (url === '/api/structured/sessions' && options.method === 'POST') {
        const payload = JSON.parse(options.body);
        expect(payload).toEqual({
          cwd: 'C:\\repo',
          provider: 'claude',
          title: 'Agent thread'
        });

        structuredSessions = [
          structuredSnapshot({
            id: 'ss-created',
            title: 'Agent thread',
            thread: {
              topic: 'Agent thread',
              topicAutoGenerated: false,
              pinned: false,
              archived: false,
              projectPath: 'C:\\repo',
              lastActivityAt: '2026-04-05T09:03:00.000Z'
            },
            updatedAt: '2026-04-05T09:03:00.000Z'
          })
        ];

        return {
          ok: true,
          json: async () => structuredSessions[0]
        };
      }

      if (String(url).startsWith('/api/state')) {
        return {
          ok: true,
          json: async () => ({ sessions: [] })
        };
      }

      throw new Error(`Unexpected apiFetch call: ${url}`);
    });

    render(
      <TerminalSessionProvider>
        <TestStructuredLifecycleConsumer />
      </TerminalSessionProvider>
    );

    await waitFor(() => {
      expect(screen.getByTestId('session-ids')).toHaveTextContent('');
    });

    await act(async () => {
      screen.getByRole('button', { name: 'create structured' }).click();
    });

    await waitFor(() => {
      expect(screen.getByTestId('session-ids')).toHaveTextContent('ss-created');
    });

    const createCalls = apiFetch.mock.calls.filter(
      ([url, options]) => url === '/api/structured/sessions' && options?.method === 'POST'
    );
    expect(createCalls).toHaveLength(1);
    expect(screen.getByTestId('structured-title')).toHaveTextContent('Agent thread');
    expect(screen.getByTestId('structured-topic')).toHaveTextContent('Agent thread');
  });

  it('renames structured sessions through the structured API route', async () => {
    let structuredSessions = [
      structuredSnapshot()
    ];

    apiFetch.mockImplementation(async (url, options = {}) => {
      if (url === '/api/terminal') {
        return {
          ok: true,
          json: async () => ({ sessions: [] })
        };
      }

      if (url === '/api/structured/sessions') {
        return {
          ok: true,
          json: async () => structuredSessions
        };
      }

      if (url === '/api/structured/sessions/ss-structured' && options.method === 'PATCH') {
        expect(JSON.parse(options.body)).toEqual({ title: 'Renamed thread' });
        structuredSessions = [
          structuredSnapshot({
            title: 'Renamed thread',
            updatedAt: '2026-04-05T09:05:00.000Z',
            thread: {
              topic: 'Renamed thread',
              topicAutoGenerated: false,
              pinned: false,
              archived: false,
              projectPath: 'C:\\repo',
              lastActivityAt: '2026-04-05T09:05:00.000Z'
            }
          })
        ];

        return {
          ok: true,
          json: async () => structuredSessions[0]
        };
      }

      if (String(url).startsWith('/api/state')) {
        return {
          ok: true,
          json: async () => ({ sessions: [] })
        };
      }

      throw new Error(`Unexpected apiFetch call: ${url}`);
    });

    render(
      <TerminalSessionProvider>
        <TestStructuredLifecycleConsumer />
      </TerminalSessionProvider>
    );

    await waitFor(() => {
      expect(screen.getByTestId('structured-title')).toHaveTextContent('Structured session');
    });

    await act(async () => {
      screen.getByRole('button', { name: 'rename structured' }).click();
    });

    await waitFor(() => {
      expect(screen.getByTestId('structured-title')).toHaveTextContent('Renamed thread');
    });

    const renameCalls = apiFetch.mock.calls.filter(
      ([url, options]) => url === '/api/structured/sessions/ss-structured' && options?.method === 'PATCH'
    );
    expect(renameCalls).toHaveLength(1);
    expect(screen.getByTestId('structured-topic')).toHaveTextContent('Renamed thread');
  });

  it('updates structured thread metadata through the structured API route', async () => {
    let structuredSessions = [
      structuredSnapshot()
    ];

    apiFetch.mockImplementation(async (url, options = {}) => {
      if (url === '/api/terminal') {
        return {
          ok: true,
          json: async () => ({ sessions: [] })
        };
      }

      if (url === '/api/structured/sessions') {
        return {
          ok: true,
          json: async () => structuredSessions
        };
      }

      if (url === '/api/structured/sessions/ss-structured/thread' && options.method === 'PATCH') {
        expect(JSON.parse(options.body)).toEqual({
          topic: 'Review Rust rewrite',
          pinned: true
        });

        const thread = {
          topic: 'Review Rust rewrite',
          topicAutoGenerated: false,
          pinned: true,
          archived: false,
          projectPath: 'C:\\repo',
          lastActivityAt: '2026-04-05T09:06:00.000Z'
        };
        structuredSessions = [
          structuredSnapshot({
            updatedAt: '2026-04-05T09:06:00.000Z',
            thread
          })
        ];

        return {
          ok: true,
          json: async () => ({ thread })
        };
      }

      if (String(url).startsWith('/api/state')) {
        return {
          ok: true,
          json: async () => ({ sessions: [] })
        };
      }

      throw new Error(`Unexpected apiFetch call: ${url}`);
    });

    render(
      <TerminalSessionProvider>
        <TestStructuredLifecycleConsumer />
      </TerminalSessionProvider>
    );

    await waitFor(() => {
      expect(screen.getByTestId('structured-topic')).toHaveTextContent('Structured session');
    });

    await act(async () => {
      screen.getByRole('button', { name: 'update structured thread' }).click();
    });

    await waitFor(() => {
      expect(screen.getByTestId('structured-topic')).toHaveTextContent('Review Rust rewrite');
    });

    const threadUpdateCalls = apiFetch.mock.calls.filter(
      ([url, options]) => url === '/api/structured/sessions/ss-structured/thread' && options?.method === 'PATCH'
    );
    expect(threadUpdateCalls).toHaveLength(1);
    expect(screen.getByTestId('structured-pinned')).toHaveTextContent('true');
  });

  it('closes structured sessions through the structured API route', async () => {
    apiFetch.mockImplementation(async (url, options = {}) => {
      if (url === '/api/terminal') {
        return {
          ok: true,
          json: async () => ({
            sessions: []
          })
        };
      }

      if (url === '/api/structured/sessions') {
        return {
          ok: true,
          json: async () => ([
            structuredSnapshot()
          ])
        };
      }

      if (url === '/api/structured/sessions/ss-structured') {
        expect(options.method).toBe('DELETE');
        return {
          ok: true,
          status: 204,
          json: async () => ({})
        };
      }

      if (String(url).startsWith('/api/state')) {
        return {
          ok: true,
          json: async () => ({
            sessions: []
          })
        };
      }

      throw new Error(`Unexpected apiFetch call: ${url}`);
    });

    render(
      <TerminalSessionProvider>
        <TestStructuredSessionConsumer />
      </TerminalSessionProvider>
    );

    await waitFor(() => {
      expect(screen.getByTestId('session-ids')).toHaveTextContent('ss-structured');
    });

    await act(async () => {
      screen.getByRole('button', { name: 'close structured' }).click();
    });

    await waitFor(() => {
      expect(screen.getByTestId('session-ids')).toHaveTextContent('');
    });
  });

  it('keeps inactive persisted sessions visible in thread groupings after restart', async () => {
    apiFetch.mockImplementation(async (url) => {
      if (url === '/api/terminal') {
        return {
          ok: true,
          json: async () => ({
            sessions: [
              {
                id: 'session-1',
                isActive: false,
                title: 'Saved thread',
                cwd: 'C:\\repo',
                updatedAt: '2026-03-12T08:00:00.000Z',
                thread: {
                  topic: 'Saved thread',
                  pinned: true,
                  archived: false,
                  projectPath: 'C:\\repo',
                  lastActivityAt: '2026-03-12T08:00:00.000Z'
                }
              },
              {
                id: 'session-2',
                isActive: false,
                title: 'Archived thread',
                cwd: 'C:\\repo',
                updatedAt: '2026-03-12T07:00:00.000Z',
                thread: {
                  topic: 'Archived thread',
                  pinned: false,
                  archived: true,
                  projectPath: 'C:\\repo',
                  lastActivityAt: '2026-03-12T07:00:00.000Z'
                }
              }
            ]
          })
        };
      }

      if (url === '/api/structured/sessions') {
        return {
          ok: true,
          json: async () => []
        };
      }

      if (String(url).startsWith('/api/state')) {
        return {
          ok: true,
          json: async () => ({
            sessions: []
          })
        };
      }

      throw new Error(`Unexpected apiFetch call: ${url}`);
    });

    render(
      <TerminalSessionProvider>
        <TestThreadStateConsumer />
      </TerminalSessionProvider>
    );

    await waitFor(() => {
      expect(screen.getByTestId('thread-group-count')).toHaveTextContent('1');
    });

    expect(screen.getByTestId('pinned-count')).toHaveTextContent('1');
    expect(screen.getByTestId('archived-count')).toHaveTextContent('1');
    expect(screen.getByTestId('thread-session-ids')).toHaveTextContent('session-1');
  });
});
